name: 'Update Initial Experiments'
description: 'Downloads and saves the initial experiments'
inputs:
  repo-path:
    description: 'The relative or absolute path to the checked out repository'
    required: true
  output-path:
    description: 'The relative file path (from the repo path) to which the downloaded experiments should be written'
    required: true
  experimenter-url:
    description: 'URL from which to fetch Nimbus experiments'
    default: 'https://experimenter.services.mozilla.com/api/v6/experiments/?is_first_run=True'
    required: false
outputs:
  changed:
    description: 'The number of files that were modified as part of the script'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-path }}
    - ${{ inputs.output-path }}
    - ${{ inputs.experimenter-url }}